import './globals.css'
import type { Metadata } from 'next'
import Footer from './components/Footer/Footer'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex flex-col min-h-screen p-10'>
        <main className='mb-20'>{children}</main>
        <Footer />
      </body>
    </html >
  )
}
